### ISSUE TITLE
마이페이지에서 입맛 설정 건너뛰기 선택 시 액티비티 스택 남아있는 이슈

### ISSUE THREAD

**Issue by jionchu** [YAPP-19th/Android-Team-2-Frontend#162]
## 👿 Problem
- 마이페이지를 통해 입맛 설정 화면에 들어간 경우, 건너뛰기 버튼을 선택하면 입맛 설정 화면이 스택에 남아있는 채로 메인 화면으로 이동하게 됩니다.
- 따라서 메인화면에서 뒤로가기 버튼을 누르면 입맛 설정 화면으로 돌아오게 됩니다.

## 🤩 Expected
- 건너뛰기 버튼 클릭 시 백스택 없애는 로직 추가해주세요~!

**Comment by junieberry** [comment]
맙소사소사,,,
