### ISSUE TITLE
홈 기본 레이아웃

### ISSUE THREAD

**Issue by junieberry** [YAPP-19th/Android-Team-2-Frontend#56]
## 목적
> 홈 기본 레이아웃 구성

## 작업 상세 내용
- [x] 홈 프래그먼트 기본 레이아웃 설정
- [x] 유저 닉네임 받아오기 

### 참고 사항
아직 api 개발 전이라서 레이아웃만 먼저 작성했습니다!

**Comment by ashwon12** [comment]
준영님 여기 이슈 조금 나누는게 좋을 것 같아요~~~
